# Generated by Django 4.2 on 2024-04-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcile',
            new_name='Article',
        ),
    ]
